# server:
#   port: 8180

# spring:
#   application:
#     name: spring-ai-chat-starter
#   cloud:
#     nacos:
#       config:
#         enabled: false
#         server-addr: 127.0.0.1:8848
#         file-extension: yaml
#       discovery:
#         enabled: false
#     compatibility-verifier:
#       enabled: false
#   config:
#     import: optional:nacos:${spring.application.name}.${spring.cloud.nacos.config.file-extension}
#   ai:
#     dashscope:
#       chat:
#         options:
#           model: qwen-turbo
#       api-key: sk-92f2045236f746d2a61edf9c97da50df
#     model:
#       chat: dashscope
#     chat:
#       enabled: true
#       model: qwen
#       default-model: qwen
#       websocket:
#         enabled: true
#       rabbitmq:
#         enabled: true
#       debug: true
#   main:
#     allow-bean-definition-overriding: true

# logging:
#   level:
#     org.springframework.ai: DEBUG
#     com.randb.springaichatstarter: DEBUG
